# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.Contestant')),
            ],
        ),
    ]
