# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_remove_lottery_lot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='lot_date',
            field=models.DateTimeField(default='2015-12-15', verbose_name='drawing date'),
        ),
    ]
