# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_lottery_lot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='lot_date',
        ),
    ]
