# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_lottery_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='lot_date',
            field=models.DateTimeField(default='2015-12-15', null=True, verbose_name='drawing date'),
        ),
    ]
